# Generated by Django 5.2.5 on 2026-01-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, unique=True)),
                ('min_experience', models.FloatField()),
                ('required_skills', models.TextField()),
                ('shortlist_score', models.IntegerField(default=70)),
                ('hold_score', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoldCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('current_employer', models.CharField(blank=True, max_length=150)),
                ('current_salary', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('relocate', models.BooleanField()),
                ('resume_link', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RejectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('current_employer', models.CharField(blank=True, max_length=150)),
                ('current_salary', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('relocate', models.BooleanField()),
                ('resume_link', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('current_employer', models.CharField(blank=True, max_length=150)),
                ('current_salary', models.CharField(blank=True, max_length=50)),
                ('expected_salary', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('relocate', models.BooleanField()),
                ('resume_link', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
