# Generated by Django 5.2.5 on 2026-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdcandidate',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='holdcandidate',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='holdcandidate',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='holdcandidate',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='holdcandidate',
            name='relocate',
        ),
        migrations.RemoveField(
            model_name='rejectedcandidate',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='rejectedcandidate',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='rejectedcandidate',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='rejectedcandidate',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='rejectedcandidate',
            name='relocate',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='interview_time',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='shortlistedcandidate',
            name='relocate',
        ),
        migrations.AlterField(
            model_name='holdcandidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='holdcandidate',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='holdcandidate',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='holdcandidate',
            name='resume_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejectedcandidate',
            name='resume_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shortlistedcandidate',
            name='resume_link',
            field=models.TextField(blank=True),
        ),
    ]
